<?php

declare(strict_types=1);

namespace FmsOData\Spec\Metadata;

/**
 * All FileMaker metadata annotations.
 *
 * Combines boolean and value annotations and adds the product/server version
 * annotations.
 */
final readonly class FMAnnotations
{
    public function __construct(
        // Boolean annotations
        public ?bool $autoGenerated = null,
        public ?bool $index = null,
        public ?bool $versionId = null,
        public ?bool $global = null,
        public ?bool $calculation = null,
        public ?bool $summary = null,
        public ?bool $computed = null,
        // Value annotations
        public ?int $maxRepetitions = null,
        public ?string $externalSecurePath = null,
        public ?string $bestRowId = null,
        public ?string $rowVersion = null,
        public ?string $tableId = null,
        public ?string $fieldId = null,
        public ?string $scriptId = null,
        public ?string $fmComment = null,
        public ?string $aiAnnotation = null,
        // Version annotations
        public ?string $productVersion = null,
        public ?string $serverVersion = null,
    ) {}
}
