<?php

declare(strict_types=1);

namespace FmsOData\Spec\Metadata;

/** FileMaker-specific boolean field annotations. */
final readonly class FMBooleanAnnotations
{
    public function __construct(
        public ?bool $autoGenerated = null,
        public ?bool $index = null,
        public ?bool $versionId = null,
        public ?bool $global = null,
        public ?bool $calculation = null,
        public ?bool $summary = null,
        public ?bool $computed = null,
    ) {}
}
